### ISSUE TITLE
Add support for openai link picker

### ISSUE THREAD

**Issue by 2fst4u** [nextcloud/notes#1052]
**Is your feature request related to a problem? Please describe.**
You can't use the openai link picker in the app. 

**Describe the solution you'd like**
The ability to use the link picker to use openai integration.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by juliushaertl** [comment]
This is already possible with using the rich text editor starting with nextcloud 26. Did you have troubles finding that or is the request specific about the plain markdown editing mode?

**Comment by 2fst4u** [comment]
This might turn into troubleshooting a different issue now, but when I try to switch to rich text editor I got the error:

```
```
App Version: 4.0.0
App Version Code: 40000090
App Flavor: play

Files App Version Code: 30240290

---

OS Version: 4.14.180-perf+(P.202303230244)
OS API Level: 31
Device: OnePlus7Pro
Manufacturer: OnePlus
Model (and Product): GM1913 (OnePlus7Pro)

---

java.lang.NullPointerException: item is null
	at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
	at io.reactivex.Single.just(Single.java:839)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.changeToEditMode(NoteDirectEditFragment.kt:329)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.handleLoadError$lambda$10(NoteDirectEditFragment.kt:198)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment.$r8$lambda$Ki_8kpNhrZywBDxHTc4EONZ3QGQ(Unknown Source:0)
	at it.niedermann.owncloud.notes.edit.NoteDirectEditFragment$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0$com-google-android-material-snackbar-Snackbar(Snackbar.java:352)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7488)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1202)
	at android.view.View.performClickInternal(View.java:7464)
	at android.view.View.access$3700(View.java:841)
	at android.view.View$PerformClick.run(View.java:28911)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```
```

**Comment by 2fst4u** [comment]
Disagree that this isn't a notes app issue. I have the integration installed on my server. The issue is that I cannot see the integration in the android app. Is this not the correct place for an android app issue?
