### ISSUE TITLE
entity.Account.getColor

### ISSUE THREAD

**Issue by hellpe** [nextcloud/notes#1063]
Please make a clear and concise description of what the bug is.

## Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots
![Screenshot_20230619-183403](https://github.com/nextcloud/notes/assets/1238320/f76f0deb-770f-4d3e-9d70-7b81a5d82d11)

## Server
Please complete the following information.
  https://valise.chapril.org

**Nextcloud configuration:**

<details>
```
App Version: 4.0.0
App Version Code: 40000090
App Flavor: fdroid

Files App Version Code: 30250090

---

OS Version: 4.19.157-perf(L752_07.6.3)
OS API Level: 31
Device: L752
Manufacturer: Crosscall
Model (and Product): Action-X5 (L752)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'int it.niedermann.owncloud.notes.persistence.entity.Account.getColor()' on a null object reference
    at it.niedermann.owncloud.notes.main.MainViewModel.postCurrentAccount(MainViewModel.java:123)
    at it.niedermann.owncloud.notes.main.MainActivity.lambda$onCreate$0$it-niedermann-owncloud-notes-main-MainActivity(MainActivity.java:176)
    at it.niedermann.owncloud.notes.main.MainActivity$$ExternalSyntheticLambda44.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7906)

    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): 
 - OS: 

## Log files
Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by hellpe** [comment]
Sorry, I accidentally posted this ticket instead of discarding it
