### ISSUE TITLE
Synchronization error

### ISSUE THREAD

**Issue by msauer75** [nextcloud/notes#1431]
Hi,

I use the latest Nextcloud version on my server and on android the latest nextcloud notes app. After I change a note I will get the synchronization error.
I removed the app and installed new but the error is the same.
I get the following message:

```
App Version: 4.3.1
App Version Code: 40030192
App Flavor: play

Files App Version Code: 30290290 (PROD)

---

OS Version: 5.10.198-android12-9-28577532-abA536BXXSDEXJB(A536BXXSDEXJB)
OS API Level: 34
Device: a53x
Manufacturer: samsung
Model (and Product): SM-A536B (a53xnaeea)

---

java.lang.Exception: {"errorType":"RuntimeException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:151)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

Is there a solution for this problem?

Thank you for your help.
BR
martin

**Comment by stefan-niedermann** [comment]
Please fill out the issue template, it is there for a reason. Especially check your server logs.

**Comment by msauer75** [comment]
After I checked the nextcloud logs, I find the problem. It was the clamav configuration. After I corrected this, it works.

**Comment by stefan-niedermann** [comment]
Great to hear, maybe you can share what was configured wrong so other users with the same issue can learn the solution?

**Comment by msauer75** [comment]
Nextcloud couldn't access clamav socket. So I have to use clamav programme and add /usr/bin to openbase_dir.
