### ISSUE TITLE
Nextcloud files app api is not responding.

### ISSUE THREAD

**Issue by gentooj** [nextcloud/notes#674]
Nextcloud Notes works as expected on my older Android device (7.1.2). I recently got the Unihertz Atom XL with Android 10, and was able to sync my Calendar, Contacts, and Tasks with Nextcloud. However, the notes app has been unable to connect to the account.

## Steps to reproduce
1. Launch Nextcloud Notes
2. Choose an account (that is confirmed to be accessible on an older Android device)
3. Allow Nextcloud Notes to access the account that is tied to the Nextcloud instance currently in use
4. Disable battery optimizations
5. Force stop both Nextcloud and Nextcloud Notes
6. Clear all storage for Nextcloud and Nextcloud Notes
7. Repeat steps 1-3

### Expected behaviour
The notes that are stored in the Nextcloud account that are currently visible in the app on an older device should be accessible as well.

### Actual behaviour
Please see 'Steps to Reproduce' section above

## Log files
```
App Version: 3.1.1
App Version Code: 3001001
App Flavor: fdroid

Files App Version Code: 30140390

---

OS Version: 4.14.141+(root.20200928.094206)
OS API Level: 29
Device: Atom_XL
Manufacturer: Unihertz
Model (and Product): Atom_XL (Atom_XL)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'long it.niedermann.owncloud.notes.shared.model.LocalAccount.getId()' on a null object reference
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$setupNotesList$11$MainActivity(MainActivity.java:405)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$NZHCdUpUXVuxQslht4rPl-lZbP8.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7161)
	at android.view.View.performClickInternal(View.java:7134)
	at android.view.View.access$3500(View.java:810)
	at android.view.View$PerformClick.run(View.java:27756)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

```

**Comment by stefan-niedermann** [comment]
Hey there,

this repository is only for the server app.
Please try these steps: https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error

Regards
Stefsn
