### ISSUE TITLE
Cannot sync Notes with my android app

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/notes#708]
Android app dev told me its a server side issue. Note that it seams to work with other users. Note also that i have lot of notes. Do you think it can be dew to some special chars ? 

Here is my android app log. 

Thanks 

```
App Version: 3.4.0
App Version Code: 3004000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.14.116(10.0.0.171C109)
OS API Level: 29
Device: HWCLT
Manufacturer: HUAWEI
Model (and Product): CLT-L29 (CLT-L29)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: La requête HTTP a échoué avec le statut HTTP :500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:178)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.deleteNote(NotesClientV1.java:57)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:126)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalStateException: {"errorType":"OCP\\Files\\ForbiddenException"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1028)
	at android.os.Binder.execTransact(Binder.java:1001)


com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: La requête HTTP a échoué avec le statut HTTP :500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:178)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.deleteNote(NotesClientV1.java:57)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:126)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalStateException: {"errorType":"OCP\\Files\\ForbiddenException"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1028)
	at android.os.Binder.execTransact(Binder.java:1001)

```

**Comment by stefan-niedermann** [comment]
@Jerome-Herbinet I think [i explicitly told you](https://github.com/stefan-niedermann/nextcloud-notes/issues/1177#issuecomment-827590788) to *not ignore* the issue template. The error message in the Android app is only saying "Server responded with error 500", so I am pretty sure that @korelstar won't be able to figure out what's going on only based on this information.

Please fill out the complete issue template including the *server* logs and the used versions.

**Comment by korelstar** [comment]
Yes, please fill out the issue template.

**Comment by Jerome-Herbinet** [comment]
## Steps to reproduce
1. Open NextCloud Notes app for android and sync (auto or manual)

### Expected behaviour
Sync

### Actual behaviour
Doesn't sync

### Screenshots
https://cloud.herbinet.fr/index.php/s/K8C37z8FcL8Zf4L

## Server
Please complete the following information.

- Notes app version: 4.04 and android app 3.1.0
- Nextcloud version: 20.0.9
- OS: Linux
- Web server: ?
- PHP version:  7.4
- Database: mySQL 5.7

**Nextcloud configuration:**

## Client
Please complete the following information.

- Browser (incl. version): 
 - OS: Android
 - NextCloud Notes app 3.1.0


## Log files
App Version: 3.4.0
App Version Code: 3004000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.14.116(10.0.0.171C109)
OS API Level: 29
Device: HWCLT
Manufacturer: HUAWEI
Model (and Product): CLT-L29 (CLT-L29)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: La requête HTTP a échoué avec le statut HTTP :500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:178)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.deleteNote(NotesClientV1.java:57)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:126)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalStateException: {"errorType":"OCP\\Files\\ForbiddenException"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1028)
	at android.os.Binder.execTransact(Binder.java:1001)


com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: La requête HTTP a échoué avec le statut HTTP :500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:178)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.deleteNote(NotesClientV1.java:57)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:126)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalStateException: {"errorType":"OCP\\Files\\ForbiddenException"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1028)
	at android.os.Binder.execTransact(Binder.java:1001)

**Comment by korelstar** [comment]
Come on, please provide more relevant information by yourself! Does the notes app work if you open it with your web browser? What's the information in the server log? Are you able to access all (!) files in your notes folder? Is there any sub folder wich cannot be accessed? What's the difference between your user account and others? ...?

See issue template:
> Add relevant parts of your `nextcloud.log` and/or your browser's JavaScript console here.

**Comment by Jerome-Herbinet** [comment]
Hello, 
I am really sorry for all that lack of information ... i didn't really have time to investigate more and provide you all what you where expecting. 
Meanwhile, i told myself that i could eventually solve my problem by totally re-installing my android client app. That's what i did and all works perfectly now.
You can now close the ticket now if you want. 
Sorry again and thank you for your work.
Sincerely,
Jerome
