### ISSUE TITLE
NullPointer if I try to choose an account

### ISSUE THREAD

**Issue by tylon85** [nextcloud/notes#725]
Since the app suddenly said it couldn't find my account in Nextcloud, I removed the account from the app and went to add it again. But now comes a NullPointerException.

```
App Version: 3.4.4
App Version Code: 3004004
App Flavor: fdroid

Files App Version Code: 30160190

---

OS Version: 4.14.199-g548ba7616dc6-ab7185844(7246365)
OS API Level: 30
Device: sunfish
Manufacturer: Google
Model (and Product): Pixel 4a (sunfish)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'int it.niedermann.owncloud.notes.persistence.entity.Account.getColor()' on a null object reference
	at it.niedermann.owncloud.notes.main.MainViewModel.postCurrentAccount(MainViewModel.java:116)
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$0$MainActivity(MainActivity.java:169)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$herSCsajIfxGZk6iBYSe7-CVE7Q.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```

**Comment by stefan-niedermann** [comment]
Please try to clear the storage if the Notes app and import your account again. You can achieve this by going to the Android settings -> Apps -> Notes -> Storage -> Clear storage. Not synchronized changes will be lost, so export them before performing those steps if possible.

If this doesn't work, feel free to [open a new issue in the correct repository of the Android client](https://github.com/stefan-niedermann/nextcloud-notes/issues/new?assignees=&labels=bug&template=bug_report.md) filling the complete issue template (it is there [for a reason](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed)).
