### ISSUE TITLE
Error when loggin

### ISSUE THREAD

**Issue by Trebor87** [nextcloud/notes#782]
I've just switched my NC provider, was working fine before

When I try and login I get the following message, shown below

I've cleared catch , and reinstalled

NextCloud client works fine, just notes giving me the error

## Steps to reproduce
1.Logging in , correct email and password gives me the following error, shown below
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Error message

## Server
Please complete the following information.

- Notes app version: 3.4.16
- Nextcloud version: 3.18.0
- OS: Android 12
- Web server: 
- PHP version: 
- Database: 

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): Brave and chrome
 - OS: 

## Log files
pp Version: 3.4.16
App Version Code: 3004016
App Flavor: fdroid

Files App Version Code: 30180090

---

OS Version: 4.9.270-g862f51bac900-ab7613625(7679548)
OS API Level: 31
Device: blueline
Manufacturer: Google
Model (and Product): Pixel 3 (blueline)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 401
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:32)
	at it.niedermann.owncloud.notes.importaccount.ImportAccountActivity.lambda$onActivityResult$5$it-niedermann-owncloud-notes-importaccount-ImportAccountActivity(ImportAccountActivity.java:97)
	at it.niedermann.owncloud.notes.importaccount.ImportAccountActivity$$ExternalSyntheticLambda6.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.IllegalStateException: <?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message>Unauthorised</message>
 </meta>
 <data/>
</ocs>

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)

```

**Comment by stefan-niedermann** [comment]
Please try to remove your account from the main Nextcloud Android app and clear the **storage** of the Nextcloud Notes Android app as [described here](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#tokenmismatchexception-and-all-others). Then add your account again.
Google does **not** clear the storage of an app when it gets uninstalled, so this should take care about removing all left overs.

If the login keeps failing, feel free to [open a new issue in the repository of the Nextcloud Notes Android app](https://github.com/stefan-niedermann/nextcloud-notes/issues/new?assignees=&labels=bug&template=bug_report.md) (this repository is only for the Notes server app).
