### ISSUE TITLE
notes app doesn't sync with server

### ISSUE THREAD

**Issue by emmeemmeesse** [nextcloud/notes#810]
hi!
my notes app on my phone doesn't sync with the notes on my server (which i access through my laptop's browser).

the app gave me this message to be reported:

```
App Version: 3.4.18
App Version Code: 3004018
App Flavor: fdroid

Files App Version Code: 20220128 (Beta)

---

OS Version: 4.9.218+(eng.root.20211027.184504)
OS API Level: 29
Device: FP3
Manufacturer: Fairphone
Model (and Product): FP3 (FP3)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 302
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:32)
	at it.niedermann.owncloud.notes.main.MainViewModel.lambda$synchronizeCapabilities$13$it-niedermann-owncloud-notes-main-MainViewModel(MainViewModel.java:411)
	at it.niedermann.owncloud.notes.main.MainViewModel$$ExternalSyntheticLambda16.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: <html>
<head><title>302 Found</title><script type="text/javascript" src="/ynh_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynh_overlay.css"><script type="text/javascript" src="/ynhtheme/custom_portal.js"></script><link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css"></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

```

anyone can help with this?

**Comment by stefan-niedermann** [comment]
1. This is the repository of thr Notes **Server app** and not of the Notes Android App
2. Your Nextcloud server is missing this very app. The Notes Android app does not work until the Notes server app has been installed on your Nextcloud server
3. Ignoring issue templates will usually not leas to any help. Please fill it out the next time instead of ignoring and deleting it (no matter which repository or project you are requesting help for)

**Comment by emmeemmeesse** [comment]
1 - sorry, i got brought here from the notes android app so i thought this was the right place.

2 - point is i have the notes server app installed though.

3 - sorry for that, i just thought that the message from the app i shared was containing already all the relevant infor,

**Comment by korelstar** [comment]
> 3 - sorry for that, i just thought that the message from the app i shared was containing already all the relevant infor,

No, this information is not sufficient. But it's not too late for using the issue template! You just need to want to do it! Yes, do it now!

**Comment by korelstar** [comment]
Issue was re-created: #811

**Comment by emmeemmeesse** [comment]
> Issue was re-created: #811

i closed this one because i reopened it in the right section. 😅

**Comment by korelstar** [comment]
It's fine, I just wanted to document this here.
